name: Release

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Release
    runs-on: ubuntu-latest
    if: (!contains(github.event.head_commit.message, '[skip ci]')) && (!contains(github.event.head_commit.message, '[ci skip]'))
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v1
        with:
          node-version: 14.4.0

      - uses: bahmutov/npm-install@v1.1.0

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release
