name: Test

on: [pull_request]

jobs:
  test:
    name: Build & Run tests
    runs-on: ubuntu-latest
    if: (!contains(github.event.head_commit.message, '[skip ci]')) && (!contains(github.event.head_commit.message, '[ci skip]'))
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16.13.2

      - uses: bahmutov/npm-install@v1.1.0

      - name: Validate types
        run: yarn -s typecheck

      - name: Lint code
        run: yarn -s lint

      - name: Run tests
        run: yarn -s test --ci
